#!/usr/bin/env python3
"""
IDF Creator Service - Fixed version
Generates IDF files from natural language descriptions or addresses
"""

from flask import Flask, request, jsonify
import json
import re
import os

app = Flask(__name__)

def safe_get(data, key, default=None):
    """Safely get value from dict with default"""
    value = data.get(key, default)
    if value is None:
        return default
    return value

def safe_divide(numerator, denominator, default=0):
    """Safely divide two numbers, handling None and zero"""
    if denominator is None or denominator == 0:
        return default
    if numerator is None:
        return default
    try:
        return numerator / denominator
    except (TypeError, ZeroDivisionError):
        return default

def safe_lower(value, default=''):
    """Safely convert to lowercase, handling None"""
    if value is None:
        return default
    try:
        return str(value).lower()
    except:
        return default

def extract_building_params(address, description=None, building_type=None, floor_area=None, num_floors=None):
    """Extract building parameters from input with safe defaults"""
    # Safe defaults
    params = {
        'building_type': safe_lower(building_type, 'office'),
        'floor_area': floor_area or 500,  # Default 500 m²
        'num_floors': num_floors or 1,     # Default 1 floor
        'address': address or '',
        'description': description or ''
    }
    
    # Validate numeric values
    if params['floor_area'] <= 0:
        params['floor_area'] = 500
    if params['num_floors'] <= 0:
        params['num_floors'] = 1
    
    # Calculate total area if not provided
    params['total_area'] = params['floor_area'] * params['num_floors']
    params['area_per_floor'] = safe_divide(params['total_area'], params['num_floors'], params['floor_area'])
    
    return params

def generate_simple_idf(params):
    """Generate a simple IDF file from parameters"""
    building_type = params['building_type']
    floor_area = params['floor_area']
    num_floors = params['num_floors']
    address = params['address']
    area_per_floor = params['area_per_floor']
    
    # Extract location info from address
    location_name = address if address else "Chicago, IL"
    
    # Generate IDF content
    idf_content = f"""!- EnergyPlus IDF File Generated by IDF Creator Service
!- Building Type: {building_type}
!- Floor Area: {floor_area} m²
!- Number of Floors: {num_floors}
!- Address: {address}

Version,9.3;

Timestep,4;

Building,
  {building_type.title()} Building,  !- Name
  0,                       !- North Axis {{deg}}
  Suburbs,                 !- Terrain
  0.04,                    !- Loads Convergence Tolerance Value
  0.40,                    !- Temperature Convergence Tolerance Value {{deltaC}}
  FullInteriorAndExterior, !- Solar Distribution
  25,                      !- Maximum Number of Warmup Days
  6;                       !- Minimum Number of Warmup Days

SimulationControl,
  No,                      !- Do Zone Sizing Calculation
  No,                      !- Do System Sizing Calculation
  No,                      !- Do Plant Sizing Calculation
  Yes,                     !- Run Simulation for Sizing Periods
  No;                      !- Run Simulation for Weather File Run Periods

RunPeriod,
  Annual,                  !- Name
  1,                       !- Begin Month
  1,                       !- Begin Day of Month
  12,                      !- End Month
  31,                      !- End Day of Month
  Sunday,                  !- Day of Week for Start Day
  No,                      !- Use Weather File Holidays and Special Days
  No,                      !- Use Weather File Daylight Saving Period
  No,                      !- Apply Weekend Holiday Rule
  Yes,                     !- Use Weather File Rain Indicators
  Yes;                     !- Use Weather File Snow Indicators

Site:Location,
  {location_name},         !- Name
  41.98,                   !- Latitude {{deg}}
  -87.92,                  !- Longitude {{deg}}
  -6.0,                    !- Time Zone {{hr}}
  205.00;                  !- Elevation {{m}}

Material,
  Wall Material,           !- Name
  MediumRough,             !- Roughness
  0.20,                    !- Thickness {{m}}
  0.04,                    !- Conductivity {{W/m-K}}
  800,                     !- Density {{kg/m3}}
  1000;                    !- Specific Heat {{J/kg-K}}

Construction,
  Exterior Wall,           !- Name
  Wall Material;           !- Layer 1

Material:NoMass,
  Roof Material,           !- Name
  0.15;                    !- Thermal Resistance {{m2-K/W}}

Construction,
  Roof,                    !- Name
  Roof Material;           !- Layer 1

WindowMaterial:SimpleGlazingSystem,
  Simple Glazing,          !- Name
  3.0,                     !- U-Factor {{W/m2-K}}
  0.6;                     !- Solar Heat Gain Coefficient

Construction,
  Window,                  !- Name
  Simple Glazing;          !- Layer 1

GlobalGeometryRules,
  UpperLeftCorner,         !- Starting Vertex Position
  CounterClockwise,        !- Vertex Entry Direction
  Absolute;                !- Coordinate System

Zone,
  Main Zone,               !- Name
  0,                       !- Direction of Relative North {{deg}}
  1,                       !- X Origin {{m}}
  1,                       !- Y Origin {{m}}
  0,                       !- Z Origin {{m}}
  1,                       !- Type
  1,                       !- Multiplier
  autocalculate,           !- Ceiling Height {{m}}
  autocalculate;           !- Volume {{m3}}

BuildingSurface:Detailed,
  Wall 1,                  !- Name
  Wall,                    !- Surface Type
  Exterior Wall,           !- Construction Name
  Main Zone,               !- Zone Name
  Outdoors,                !- Outside Boundary Condition
  ,                        !- Outside Boundary Condition Object
  SunExposed,              !- Sun Exposure
  WindExposed,             !- Wind Exposure
  0.5,                     !- View Factor to Ground
  4,                       !- Number of Vertices
  0,0,3,                   !- X,Y,Z Vertex 1 {{m}}
  10,0,3,                  !- X,Y,Z Vertex 2 {{m}}
  10,0,0,                  !- X,Y,Z Vertex 3 {{m}}
  0,0,0;                   !- X,Y,Z Vertex 4 {{m}}

FenestrationSurface:Detailed,
  Window 1,                !- Name
  Window,                  !- Surface Type
  Window,                  !- Construction Name
  Wall 1,                  !- Building Surface Name
  ,                        !- Outside Boundary Condition Object
  0.5,                     !- View Factor to Ground
  ,                        !- Frame and Divider Name
  1,                       !- Multiplier
  4,                       !- Number of Vertices
  2,0,2.5,                 !- X,Y,Z Vertex 1 {{m}}
  8,0,2.5,                 !- X,Y,Z Vertex 2 {{m}}
  8,0,0.5,                 !- X,Y,Z Vertex 3 {{m}}
  2,0,0.5;                 !- X,Y,Z Vertex 4 {{m}}

Lights,
  Main Zone Lights,        !- Name
  Main Zone,               !- Zone or ZoneList Name
  Office Lighting,         !- Schedule Name
  Watts/Area,              !- Design Level Calculation Method
  10.76,                   !- Lighting Level {{W/m2}}
  ,                        !- Number of People
  ,                        !- People per Zone
  0.0,                     !- Fraction Return Air
  0.0,                     !- Fraction Radiant
  0.0,                     !- Fraction Visible
  0.0,                     !- Fraction Replaceable
  General;                 !- End-Use Subcategory

Schedule:Compact,
  Office Lighting,         !- Name
  Any Number,              !- Schedule Type Limits Name
  Through: 12/31,          !- Field 1
  For: Weekdays,           !- Field 2
  Until: 08:00,0,          !- Field 3
  Until: 18:00,1,          !- Field 4
  Until: 24:00,0,          !- Field 5
  For: Weekends,           !- Field 6
  Until: 24:00,0;          !- Field 7

ElectricEquipment,
  Main Zone Equipment,     !- Name
  Main Zone,               !- Zone or ZoneList Name
  Office Equipment,        !- Schedule Name
  Watts/Area,              !- Design Level Calculation Method
  8.0,                     !- Equipment Level {{W/m2}}
  ,                        !- Number of People
  ,                        !- People per Zone
  0.0,                     !- Fraction Latent
  0.3,                     !- Fraction Radiant
  0.0,                     !- Fraction Lost
  General;                 !- End-Use Subcategory

Schedule:Compact,
  Office Equipment,        !- Name
  Any Number,              !- Schedule Type Limits Name
  Through: 12/31,          !- Field 1
  For: Weekdays,           !- Field 2
  Until: 08:00,0,          !- Field 3
  Until: 18:00,1,          !- Field 4
  Until: 24:00,0,          !- Field 5
  For: Weekends,           !- Field 6
  Until: 24:00,0;          !- Field 7

People,
  Main Zone People,         !- Name
  Main Zone,               !- Zone or ZoneList Name
  Office Occupancy,         !- Number of People Schedule Name
  People/Area,              !- Number of People Calculation Method
  0.05,                    !- Number of People
  ,                        !- People per Zone
  ,                        !- Zone Floor Area per Person {{m2/person}}
  Office Activity,         !- Activity Level Schedule Name
  ,                        !- Carbon Dioxide Generation Rate {{m3/s-W}}
  Yes,                     !- Enable ASHRAE 55 Comfort Warnings
  ZoneAveraged,            !- Mean Radiant Temperature Calculation Type
  ,                        !- Surface Name/Angle Factor List Name
  ,                        !- Work Efficiency Schedule Name
  ClothingInsulationSchedule,  !- Clothing Insulation Calculation Method
  ,                        !- Clothing Insulation Calculation Method Schedule Name
  ,                        !- Air Velocity Schedule Name
  ,                        !- Thermal Comfort Model 1 Type
  ,                        !- Thermal Comfort Model 2 Type
  ,                        !- Thermal Comfort Model 3 Type
  ,                        !- Thermal Comfort Model 4 Type
  ,                        !- Thermal Comfort Model 5 Type
  ,                        !- Thermal Comfort Model 6 Type
  ,                        !- Thermal Comfort Model 7 Type
  ;                        !- Thermal Comfort Model 1 Name

Schedule:Compact,
  Office Occupancy,         !- Name
  Any Number,               !- Schedule Type Limits Name
  Through: 12/31,           !- Field 1
  For: Weekdays,            !- Field 2
  Until: 08:00,0,           !- Field 3
  Until: 18:00,1,           !- Field 4
  Until: 24:00,0,           !- Field 5
  For: Weekends,            !- Field 6
  Until: 24:00,0;           !- Field 7

Output:Variable,
  *,                       !- Key Value
  Site Outdoor Air Drybulb Temperature,  !- Variable Name
  Hourly;                  !- Reporting Frequency

Output:Variable,
  *,                       !- Key Value
  Zone Mean Air Temperature,  !- Variable Name
  Hourly;                  !- Reporting Frequency

Output:Meter,
  Electricity:Facility,    !- Key Name
  Hourly;                  !- Reporting Frequency

Output:Meter,
  NaturalGas:Facility,     !- Key Name
  Hourly;                  !- Reporting Frequency
"""
    
    return idf_content

@app.route('/health', methods=['GET'])
@app.route('/healthz', methods=['GET'])
def health():
    """Health check endpoint"""
    return jsonify({
        "status": "healthy",
        "service": "IDF Creator Service",
        "version": "1.0.0"
    }), 200

@app.route('/generate', methods=['POST'])
def generate():
    """Generate IDF file from natural language description or address"""
    try:
        # Get request data
        data = request.get_json() or {}
        
        # Extract parameters safely
        address = safe_get(data, 'address', '')
        description = safe_get(data, 'description', '')
        building_type = safe_get(data, 'building_type')
        floor_area = safe_get(data, 'floor_area')
        num_floors = safe_get(data, 'num_floors')
        total_area = safe_get(data, 'total_area')
        
        # Use description if address is not provided
        if not address and description:
            address = description
        
        # Extract building parameters with safe defaults
        params = extract_building_params(
            address=address,
            description=description,
            building_type=building_type,
            floor_area=floor_area,
            num_floors=num_floors
        )
        
        # Generate IDF content
        idf_content = generate_simple_idf(params)
        
        # Return success response
        return jsonify({
            "success": True,
            "message": "IDF generated successfully",
            "idf_content": idf_content,
            "parameters": params
        }), 200
        
    except Exception as e:
        # Return error response
        return jsonify({
            "success": False,
            "message": f"Error generating IDF: {str(e)}"
        }), 500

@app.route('/', methods=['GET'])
def index():
    """Root endpoint"""
    return jsonify({
        "service": "IDF Creator Service",
        "version": "1.0.0",
        "endpoints": {
            "POST /generate": "Generate IDF file from address/description",
            "GET /health": "Health check"
        }
    }), 200

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=True)

